//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaptureTheChris.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaptureTheChris.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{9PG8UF6Z6HKPJZDSZC8M7SZEKBB}.
        /// </summary>
        public static string FlagEnigma {
            get {
                return ResourceManager.GetString("FlagEnigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{LTQJWF364VPTEPPEJBSV8V926G8}.
        /// </summary>
        public static string FlagGuessNumber {
            get {
                return ResourceManager.GetString("FlagGuessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{FKGMFR4EUZ28KFHGDDA7U449DUJ}.
        /// </summary>
        public static string FlagHangman {
            get {
                return ResourceManager.GetString("FlagHangman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{FSZVKF43JVNNRY4FY4K6PQ4TANN}.
        /// </summary>
        public static string FlagKeyOnPendrive {
            get {
                return ResourceManager.GetString("FlagKeyOnPendrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{2UFDMBMN52KEY2K74REE3LHSNQB}.
        /// </summary>
        public static string FlagOneFromMagda {
            get {
                return ResourceManager.GetString("FlagOneFromMagda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{5TAXUZXD6NCWUGZ2ZQ9AF3YBKZV}.
        /// </summary>
        public static string FlagOneFromPaper {
            get {
                return ResourceManager.GetString("FlagOneFromPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{HZVFA8NHY6DA3KQ9JGJDZ9DJQ52}.
        /// </summary>
        public static string FlagProjectEuler {
            get {
                return ResourceManager.GetString("FlagProjectEuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{4F5ZPFWB8KKS2JUSNXE9DH2EEVT}.
        /// </summary>
        public static string FlagSimonSays {
            get {
                return ResourceManager.GetString("FlagSimonSays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{476FNER63JABTF933FKNDRD48YJ}.
        /// </summary>
        public static string FlagSudoku {
            get {
                return ResourceManager.GetString("FlagSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{EJ9BLW4FGJ8TSY3RG8QAWJ736CU}.
        /// </summary>
        public static string FlagTrivia {
            get {
                return ResourceManager.GetString("FlagTrivia", resourceCulture);
            }
        }
    }
}
