//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaptureTheChris.Trivia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaptureTheChris.Trivia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to czerwone buty.
        /// </summary>
        internal static string Answer1 {
            get {
                return ResourceManager.GetString("Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zielon.
        /// </summary>
        internal static string Answer10 {
            get {
                return ResourceManager.GetString("Answer10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kurczak.
        /// </summary>
        internal static string Answer11 {
            get {
                return ResourceManager.GetString("Answer11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roksana węgiel.
        /// </summary>
        internal static string Answer12 {
            get {
                return ResourceManager.GetString("Answer12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bonding.
        /// </summary>
        internal static string Answer2 {
            get {
                return ResourceManager.GetString("Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11/09/2017.
        /// </summary>
        internal static string Answer3 {
            get {
                return ResourceManager.GetString("Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Answer4 {
            get {
                return ResourceManager.GetString("Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ulewa.
        /// </summary>
        internal static string Answer5 {
            get {
                return ResourceManager.GetString("Answer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eminem.
        /// </summary>
        internal static string Answer6 {
            get {
                return ResourceManager.GetString("Answer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gówno.
        /// </summary>
        internal static string Answer7 {
            get {
                return ResourceManager.GetString("Answer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monster.
        /// </summary>
        internal static string Answer8 {
            get {
                return ResourceManager.GetString("Answer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to combinesinglerow.
        /// </summary>
        internal static string Answer9 {
            get {
                return ResourceManager.GetString("Answer9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co najlepiej uziemia?.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakiego koloru był balon w filmiku urodzinowym?.
        /// </summary>
        internal static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na co Mati miał ochotę zjeść całe?.
        /// </summary>
        internal static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Która czternastolatka skradła Ci serce?.
        /// </summary>
        internal static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co Ola robiła z koleżanką w toalecie?.
        /// </summary>
        internal static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data pierwszego razu w Szwecji w formacie DD/MM/RRRR..
        /// </summary>
        internal static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokąd nocą tupta jeż?.
        /// </summary>
        internal static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;…​ jest mą siostrą, strumień bratem, A każde z żywych stworzeń to mój druh,&quot;.
        /// </summary>
        internal static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kim jest Magda w kapturze?.
        /// </summary>
        internal static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co jedzą karasie?.
        /// </summary>
        internal static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czego nie należy łączyć z wódką?.
        /// </summary>
        internal static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakiej funkcji użyć jak coś nie działa w Bundlach?.
        /// </summary>
        internal static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
    }
}
