//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaptureTheChris.Flags.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaptureTheChris.Flags.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{sto_lat!}.
        /// </summary>
        public static string FlagCake {
            get {
                return ResourceManager.GetString("FlagCake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{camaro_to_to_nie_jest}.
        /// </summary>
        public static string FlagCar {
            get {
                return ResourceManager.GetString("FlagCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{baby_to_zło}.
        /// </summary>
        public static string FlagCave {
            get {
                return ResourceManager.GetString("FlagCave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{amarantowy_błękit}.
        /// </summary>
        public static string FlagEnigma {
            get {
                return ResourceManager.GetString("FlagEnigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{klasyczny_Mariusz}.
        /// </summary>
        public static string FlagFoosball {
            get {
                return ResourceManager.GetString("FlagFoosball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{uwolnić_merge}.
        /// </summary>
        public static string FlagGerrit {
            get {
                return ResourceManager.GetString("FlagGerrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{siedem_to_szczęśliwa_cyfra}.
        /// </summary>
        public static string FlagGuessNumber {
            get {
                return ResourceManager.GetString("FlagGuessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{fajny_siusiak}.
        /// </summary>
        public static string FlagHangman {
            get {
                return ResourceManager.GetString("FlagHangman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{w_metrze_i_w_swetrze}.
        /// </summary>
        public static string FlagMetro {
            get {
                return ResourceManager.GetString("FlagMetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{żebyś_kurwo_umarła}.
        /// </summary>
        public static string FlagOrigami {
            get {
                return ResourceManager.GetString("FlagOrigami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{pochodne_górą}.
        /// </summary>
        public static string FlagProjectEuler {
            get {
                return ResourceManager.GetString("FlagProjectEuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{ważniejsze_to_co_mówi_Magda}.
        /// </summary>
        public static string FlagSimonSays {
            get {
                return ResourceManager.GetString("FlagSimonSays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\home\\site\\wwwroot\\Flags.config.
        /// </summary>
        public static string FlagsPath {
            get {
                return ResourceManager.GetString("FlagsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{wolę_szachy}.
        /// </summary>
        public static string FlagSudoku {
            get {
                return ResourceManager.GetString("FlagSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC{to_nie_było_10_pytań}.
        /// </summary>
        public static string FlagTrivia {
            get {
                return ResourceManager.GetString("FlagTrivia", resourceCulture);
            }
        }
    }
}
